name: 🔄 Update Currency Rates

on:
  #schedule:
  #  - cron: '0 6-17 * * 1-5'
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  parse-and-update:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    # Даем процессу официальное разрешение удалять логи через консоль
    permissions:
      actions: write
    
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v5

      - name: 🐍 Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: 📦 Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: 🔄 Run Parser
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        run: python update_sheets.py

      - name: 🗑️ Native Delete Run History
        if: success()
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh run delete ${{ github.run_id }}
